production:
  adapter: postgresql
  username: pablo_almeida 
  password: admin 
  database: azeitanaro_production
  host: localhost
  port: 5432

development:
  adapter: postgresql
  username: pablo_almeida 
  password: admin 
  database: azeitanaro_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  username: pablo_almeida 
  password: admin 
  database: azeitanaro_test
  host: localhost
  port: 5432