production:
  adapter: postgresql
  username: postgres 
  password: postgres 
  database: azeitanaro_production
  host: localhost
  port: 5432

development:
  adapter: postgresql
  username: postgres 
  password: postgres 
  database: azeitanaro_development
  host: localhost
  port: 5432

test:
  adapter: postgresql
  username: postgres 
  password: postgres 
  database: azeitanaro_test
  host: localhost
  port: 5432